name: Build

on:
  push:
    branches:
      - main
  

jobs:
  prettier:
    name: Format with Prettier
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch prebuilt Code package from cache
        id: cache-vscode
        uses: actions/cache@v3
        with:
          path: lib/vscode-reh-web-*
          key: vscode-reh-package-123
          restore-keys: |
            vscode-reh-package-
          
      - run: find. lib/

 
